name: Deploy Lambda functions in the knowledge repository
on: [push]
jobs:

  deploy_create_art_of_the_lambda:
    name: Deploy CreateArtOfTheDayLambda
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: default deploy
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: CreateArtOfTheDayLambda 
          source: artoftheday/CreateArtOfTheDayLambda/lamba_function.py
  
  deploy_create_daily_digest_lambda:
    name: Deploy GetArtOfTheDayAPILambda
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: default deploy
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: GetArtOfTheDayAPILambda
          source: artoftheday/GetArtOfTheDayAPILambda/lambda_function.py
  
